### ISSUE TITLE
Multi-threading?

### ISSUE THREAD

**Issue by njlr** [connorhaigh/SubstreamSharp#4]
Hi, 

Thanks for an interesting project!

I was wondering how the `SubStream` behaves when it is accessed from multiple threads? 
I did not notice any locking / atomics in the source-code so is this not a supported use-case?

Also worth a look: https://github.com/Azure/azure-storage-net/blob/b0d47bfd4c1c0dcbe60eaf373e2977cd7405aa5f/Lib/Common/Blob/SubStream.cs

Thanks!

**Comment by connorhaigh** [comment]
Hey, sorry for taking so long to get back to you on this!

The behaviour of a `Substream` instance when accessed from multiple threads would generally be dependent on the behaviour of the underlying stream, with one main exception. While a substream will `Seek` before each read/write operation (to ensure that the operation reads from/writes to the expected position), because the underlying stream itself is not locked in any way (as you mentioned) between the seek and subsequent mutation, there is an opportunity for this to be interrupted if there are multiplte threads using the same substream instance. Ergo, I would recommend the use of the `Stream.Synchronized` method which you could use to wrap a `Substream` instance to ensure thread safety: https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.synchronized?view=net-6.0

**Comment by njlr** [comment]
> Hey, sorry for taking so long to get back to you on this!
> 
> The behaviour of a `Substream` instance when accessed from multiple threads would generally be dependent on the behaviour of the underlying stream, with one main exception. While a substream will `Seek` before each read/write operation (to ensure that the operation reads from/writes to the expected position), because the underlying stream itself is not locked in any way (as you mentioned) between the seek and subsequent mutation, there is an opportunity for this to be interrupted if there are multiplte threads using the same substream instance. Ergo, I would recommend the use of the `Stream.Synchronized` method which you could use to wrap a `Substream` instance to ensure thread safety: https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.synchronized?view=net-6.0

I wasn't aware of `Stream.Synchronized` - it looks like a great solution. Thanks!
